### ISSUE TITLE
Query for Tokens of an Account returns error 503

### ISSUE THREAD

**Issue by yazu-codes** [hiero-ledger/hiero-mirror-node#1685]
**Detailed Description**
Querying the mirror node api for account's tokens returns an error with status 503 and message "Service unavailable" 

**Actual Behavior**
1. Query this:
http://testnet.mirrornode.hedera.com/api/v1/tokens?account.id=0.0.xxxxxx, where xxxxxx is the account number

**Expected Behavior**
I expected to be able to retrieve the specified account's tokens information.

**Comment by steven-sheehy** [comment]
This has duplicates https://github.com/hashgraph/hedera-mirror-node/issues/1586 and has already been fixed. To workaround, you can drop the shard and realm portion of the account id.
