### ISSUE TITLE
Add missing endpoints to monitor dashboard

### ISSUE THREAD

**Issue by steven-sheehy** [hiero-ledger/hiero-mirror-node#4050]
### Problem

The monitor dashboard has not been updated properly whenever we add new endpoints.

### Solution

* Add new checks for every endpoint that is missing in the [monitor](https://github.com/hashgraph/hedera-mirror-node/tree/main/hedera-mirror-rest/monitoring)
* Add properties to control enablement of checks

**Comment by MarcKriguerAtHedera** [comment]
Splitting blocks tests into its own ticket.
