### ISSUE TITLE
Swagger UI does not interpolate contract id properly

### ISSUE THREAD

**Issue by mshakeg** [hiero-ledger/hiero-mirror-node#4887]
### Description

The swagger ui does not interpolate the contract id for at least the following endpoint:
https://testnet.mirrornode.hedera.com/api/v1/docs/#/contracts/getContractById

The request it submits is a GET `https://testnet.mirrornode.hedera.com/api/v1/contracts/%7BcontractIdOrAddressPathParam%7D`

Or as a curl:
```
curl -X 'GET' \
  'https://testnet.mirrornode.hedera.com/api/v1/contracts/{contractIdOrAddressPathParam}' \
  -H 'accept: application/json'
```

As shown above the `contractIdOrAddressPathParam` is not interpolated properly using the `contractIdOrAddress` input

### Steps to reproduce

1. Attempt a call on at least the following swagger endpoint and observe the described issue. `https://testnet.mirrornode.hedera.com/api/v1/contracts/%7BcontractIdOrAddressPathParam%7D`

### Hedera network

testnet

### Version

latest

**Comment by steven-sheehy** [comment]
Thanks for the ticket. Looks like it's due to us using `/api/v1/contracts/{contractIdOrAddressPathParam}` instead of `/api/v1/contracts/{contractIdOrAddress}` for all of our contract APIs.
