### ISSUE TITLE
HIP-584: Add custom error for precompiles not supported

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hiero-ledger/hiero-mirror-node#5634]
### Problem

We need to provide a way for the json-rpc relay to distinguish which calls to propagate towards consensus nodes and which to mirror-node. This is needed because we still don't support `eth_call` with precompiles on mirror-node side. We might have a call to a contract's method which internally invoke a precompile. In this case the transaction won't provide correct result so we need to mark it as invalid and the json-rpc could send the transaction towards the consensus-node.

### Solution

Add a custom error message on mirror-node side that shows we don't support precompile calls.

**Comment by steven-sheehy** [comment]
I'm against adding any more fields to the error response. If mirror node doesn't implement something just return a 501 NOT_IMPLEMENTED like it currently does for estimate gas.
