### ISSUE TITLE
HIP-584: Acceptance tests for `eth_estimateGas` with ERC transfer methods

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hiero-ledger/hiero-mirror-node#5676]
### Problem

We need to provide acceptance tests for eth_estimateGas that invokes precompiles related to ERC transfer methods.

### Solution

Provide acceptance tests for `ERCTransferPrecompile`.

**Comment by bibitibooo1** [comment]
Not merged, but done. Waiting for Charlie team.
