### ISSUE TITLE
HIP-584: Acceptance tests for `eth_estimateGas` with crypto transfer methods

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hiero-ledger/hiero-mirror-node#5680]
### Problem

We need to provide acceptance tests for eth_estimateGas that invokes crypto transfer methods.

### Solution

Provide acceptance tests for `TransferPrecompile`.

**Comment by yiliev0** [comment]
Done in https://github.com/hashgraph/hedera-mirror-node/pull/6241
